// Code generated by protoc-gen-go. DO NOT EDIT.
// source: event.proto

/*
Package jalindi is a generated protocol buffer package.

It is generated from these files:
	event.proto

It has these top-level messages:
	PostEventRequest
	PostEventResponse
	PostEventListRequest
	PostEventListResponse
	Event
	Client
*/
package jalindi

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PostEventRequest struct {
	Event       *Event  `protobuf:"bytes,3,opt,name=event" json:"event,omitempty"`
	Client      *Client `protobuf:"bytes,4,opt,name=client" json:"client,omitempty"`
	BrowserUuid string  `protobuf:"bytes,1,opt,name=browser_uuid,json=browserUuid" json:"browser_uuid,omitempty"`
	RequestUuid string  `protobuf:"bytes,2,opt,name=request_uuid,json=requestUuid" json:"request_uuid,omitempty"`
	UserAgent   string  `protobuf:"bytes,5,opt,name=user_agent,json=userAgent" json:"user_agent,omitempty"`
	Referer     string  `protobuf:"bytes,6,opt,name=referer" json:"referer,omitempty"`
}

func (m *PostEventRequest) Reset()                    { *m = PostEventRequest{} }
func (m *PostEventRequest) String() string            { return proto.CompactTextString(m) }
func (*PostEventRequest) ProtoMessage()               {}
func (*PostEventRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PostEventRequest) GetEvent() *Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *PostEventRequest) GetClient() *Client {
	if m != nil {
		return m.Client
	}
	return nil
}

func (m *PostEventRequest) GetBrowserUuid() string {
	if m != nil {
		return m.BrowserUuid
	}
	return ""
}

func (m *PostEventRequest) GetRequestUuid() string {
	if m != nil {
		return m.RequestUuid
	}
	return ""
}

func (m *PostEventRequest) GetUserAgent() string {
	if m != nil {
		return m.UserAgent
	}
	return ""
}

func (m *PostEventRequest) GetReferer() string {
	if m != nil {
		return m.Referer
	}
	return ""
}

type PostEventResponse struct {
}

func (m *PostEventResponse) Reset()                    { *m = PostEventResponse{} }
func (m *PostEventResponse) String() string            { return proto.CompactTextString(m) }
func (*PostEventResponse) ProtoMessage()               {}
func (*PostEventResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type PostEventListRequest struct {
	Events      []*Event `protobuf:"bytes,3,rep,name=events" json:"events,omitempty"`
	Client      *Client  `protobuf:"bytes,4,opt,name=client" json:"client,omitempty"`
	BrowserUuid string   `protobuf:"bytes,1,opt,name=browser_uuid,json=browserUuid" json:"browser_uuid,omitempty"`
	RequestUuid string   `protobuf:"bytes,2,opt,name=request_uuid,json=requestUuid" json:"request_uuid,omitempty"`
	UserAgent   string   `protobuf:"bytes,5,opt,name=user_agent,json=userAgent" json:"user_agent,omitempty"`
	Referer     string   `protobuf:"bytes,6,opt,name=referer" json:"referer,omitempty"`
}

func (m *PostEventListRequest) Reset()                    { *m = PostEventListRequest{} }
func (m *PostEventListRequest) String() string            { return proto.CompactTextString(m) }
func (*PostEventListRequest) ProtoMessage()               {}
func (*PostEventListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *PostEventListRequest) GetEvents() []*Event {
	if m != nil {
		return m.Events
	}
	return nil
}

func (m *PostEventListRequest) GetClient() *Client {
	if m != nil {
		return m.Client
	}
	return nil
}

func (m *PostEventListRequest) GetBrowserUuid() string {
	if m != nil {
		return m.BrowserUuid
	}
	return ""
}

func (m *PostEventListRequest) GetRequestUuid() string {
	if m != nil {
		return m.RequestUuid
	}
	return ""
}

func (m *PostEventListRequest) GetUserAgent() string {
	if m != nil {
		return m.UserAgent
	}
	return ""
}

func (m *PostEventListRequest) GetReferer() string {
	if m != nil {
		return m.Referer
	}
	return ""
}

type PostEventListResponse struct {
}

func (m *PostEventListResponse) Reset()                    { *m = PostEventListResponse{} }
func (m *PostEventListResponse) String() string            { return proto.CompactTextString(m) }
func (*PostEventListResponse) ProtoMessage()               {}
func (*PostEventListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type Event struct {
	Timestamp *google_protobuf.Timestamp `protobuf:"bytes,1,opt,name=timestamp" json:"timestamp,omitempty"`
	Type      string                     `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
	Group     string                     `protobuf:"bytes,3,opt,name=group" json:"group,omitempty"`
	Action    string                     `protobuf:"bytes,4,opt,name=action" json:"action,omitempty"`
	Amount    int64                      `protobuf:"varint,5,opt,name=amount" json:"amount,omitempty"`
}

func (m *Event) Reset()                    { *m = Event{} }
func (m *Event) String() string            { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()               {}
func (*Event) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Event) GetTimestamp() *google_protobuf.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *Event) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Event) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

func (m *Event) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *Event) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type Client struct {
	Name            string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Version         string `protobuf:"bytes,2,opt,name=version" json:"version,omitempty"`
	Platform        string `protobuf:"bytes,3,opt,name=platform" json:"platform,omitempty"`
	PlatformVersion string `protobuf:"bytes,4,opt,name=platform_version,json=platformVersion" json:"platform_version,omitempty"`
	DeviceName      string `protobuf:"bytes,5,opt,name=device_name,json=deviceName" json:"device_name,omitempty"`
	Experiment      bool   `protobuf:"varint,6,opt,name=experiment" json:"experiment,omitempty"`
}

func (m *Client) Reset()                    { *m = Client{} }
func (m *Client) String() string            { return proto.CompactTextString(m) }
func (*Client) ProtoMessage()               {}
func (*Client) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Client) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Client) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Client) GetPlatform() string {
	if m != nil {
		return m.Platform
	}
	return ""
}

func (m *Client) GetPlatformVersion() string {
	if m != nil {
		return m.PlatformVersion
	}
	return ""
}

func (m *Client) GetDeviceName() string {
	if m != nil {
		return m.DeviceName
	}
	return ""
}

func (m *Client) GetExperiment() bool {
	if m != nil {
		return m.Experiment
	}
	return false
}

func init() {
	proto.RegisterType((*PostEventRequest)(nil), "jalindi.PostEventRequest")
	proto.RegisterType((*PostEventResponse)(nil), "jalindi.PostEventResponse")
	proto.RegisterType((*PostEventListRequest)(nil), "jalindi.PostEventListRequest")
	proto.RegisterType((*PostEventListResponse)(nil), "jalindi.PostEventListResponse")
	proto.RegisterType((*Event)(nil), "jalindi.Event")
	proto.RegisterType((*Client)(nil), "jalindi.Client")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for JalindiService service

type JalindiServiceClient interface {
	PostEvent(ctx context.Context, in *PostEventRequest, opts ...grpc.CallOption) (*PostEventResponse, error)
	PostEventList(ctx context.Context, in *PostEventListRequest, opts ...grpc.CallOption) (*PostEventListResponse, error)
}

type jalindiServiceClient struct {
	cc *grpc.ClientConn
}

func NewJalindiServiceClient(cc *grpc.ClientConn) JalindiServiceClient {
	return &jalindiServiceClient{cc}
}

func (c *jalindiServiceClient) PostEvent(ctx context.Context, in *PostEventRequest, opts ...grpc.CallOption) (*PostEventResponse, error) {
	out := new(PostEventResponse)
	err := grpc.Invoke(ctx, "/jalindi.JalindiService/PostEvent", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jalindiServiceClient) PostEventList(ctx context.Context, in *PostEventListRequest, opts ...grpc.CallOption) (*PostEventListResponse, error) {
	out := new(PostEventListResponse)
	err := grpc.Invoke(ctx, "/jalindi.JalindiService/PostEventList", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for JalindiService service

type JalindiServiceServer interface {
	PostEvent(context.Context, *PostEventRequest) (*PostEventResponse, error)
	PostEventList(context.Context, *PostEventListRequest) (*PostEventListResponse, error)
}

func RegisterJalindiServiceServer(s *grpc.Server, srv JalindiServiceServer) {
	s.RegisterService(&_JalindiService_serviceDesc, srv)
}

func _JalindiService_PostEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JalindiServiceServer).PostEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/jalindi.JalindiService/PostEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JalindiServiceServer).PostEvent(ctx, req.(*PostEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JalindiService_PostEventList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostEventListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JalindiServiceServer).PostEventList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/jalindi.JalindiService/PostEventList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JalindiServiceServer).PostEventList(ctx, req.(*PostEventListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _JalindiService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "jalindi.JalindiService",
	HandlerType: (*JalindiServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PostEvent",
			Handler:    _JalindiService_PostEvent_Handler,
		},
		{
			MethodName: "PostEventList",
			Handler:    _JalindiService_PostEventList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "event.proto",
}

func init() { proto.RegisterFile("event.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 476 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x53, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0xa4, 0x71, 0xeb, 0x31, 0xb4, 0x65, 0x28, 0x60, 0x2c, 0xb5, 0x0d, 0x11, 0x82, 0x72,
	0x71, 0xa5, 0x70, 0xe1, 0x8a, 0x80, 0x0b, 0x42, 0xa8, 0x32, 0x3f, 0xd7, 0xc8, 0x49, 0x26, 0xd1,
	0x22, 0xdb, 0x6b, 0x76, 0xd7, 0x01, 0x9e, 0x85, 0x17, 0xe0, 0x29, 0x78, 0x16, 0x4e, 0x3c, 0x07,
	0xda, 0xd9, 0xb5, 0x09, 0x25, 0x3c, 0x00, 0x37, 0xcf, 0x37, 0xdf, 0xce, 0xcc, 0x37, 0xf3, 0x19,
	0x62, 0x5a, 0x53, 0x6d, 0xb2, 0x46, 0x49, 0x23, 0x71, 0xf7, 0x43, 0x51, 0x8a, 0x7a, 0x21, 0xd2,
	0xd3, 0x95, 0x94, 0xab, 0x92, 0xce, 0x19, 0x9e, 0xb5, 0xcb, 0x73, 0x23, 0x2a, 0xd2, 0xa6, 0xa8,
	0x1a, 0xc7, 0x1c, 0xff, 0x08, 0xe0, 0xf0, 0x42, 0x6a, 0xf3, 0xc2, 0xbe, 0xce, 0xe9, 0x63, 0x4b,
	0xda, 0xe0, 0x7d, 0x18, 0x72, 0xb5, 0x64, 0x30, 0x0a, 0xce, 0xe2, 0xc9, 0x7e, 0xe6, 0xcb, 0x65,
	0x8e, 0xe5, 0x92, 0xf8, 0x10, 0xc2, 0x79, 0x29, 0x2c, 0x6d, 0x87, 0x69, 0x07, 0x3d, 0xed, 0x19,
	0xc3, 0xb9, 0x4f, 0xe3, 0x3d, 0xb8, 0x36, 0x53, 0xf2, 0x93, 0x26, 0x35, 0x6d, 0x5b, 0xb1, 0x48,
	0x82, 0x51, 0x70, 0x16, 0xe5, 0xb1, 0xc7, 0xde, 0xb5, 0x62, 0x61, 0x29, 0xca, 0x35, 0x77, 0x94,
	0xab, 0x8e, 0xe2, 0x31, 0xa6, 0x1c, 0x03, 0xb4, 0xb6, 0x44, 0xb1, 0xb2, 0x2d, 0x87, 0x4c, 0x88,
	0x2c, 0xf2, 0xd4, 0x02, 0x98, 0xc0, 0xae, 0xa2, 0x25, 0x29, 0x52, 0x49, 0xc8, 0xb9, 0x2e, 0x1c,
	0xdf, 0x84, 0x1b, 0x1b, 0x0a, 0x75, 0x23, 0x6b, 0x4d, 0xe3, 0x9f, 0x01, 0x1c, 0xf5, 0xe8, 0x2b,
	0xa1, 0x7b, 0xed, 0x0f, 0x20, 0x64, 0x79, 0x3a, 0x19, 0x8c, 0x06, 0x5b, 0xc4, 0xfb, 0xec, 0x7f,
	0xa3, 0xfe, 0x0e, 0xdc, 0xba, 0xa4, 0xd3, 0x6f, 0xe0, 0x6b, 0x00, 0x43, 0x46, 0xf1, 0x09, 0x44,
	0xbd, 0x2d, 0x78, 0xbc, 0x78, 0x92, 0x66, 0xce, 0x38, 0x59, 0x67, 0x9c, 0xec, 0x6d, 0xc7, 0xc8,
	0x7f, 0x93, 0x11, 0x61, 0xc7, 0x7c, 0x69, 0xc8, 0x0f, 0xcc, 0xdf, 0x78, 0x04, 0xc3, 0x95, 0x92,
	0x6d, 0xc3, 0xe6, 0x89, 0x72, 0x17, 0xe0, 0x6d, 0x08, 0x8b, 0xb9, 0x11, 0xb2, 0xe6, 0x75, 0x45,
	0xb9, 0x8f, 0x18, 0xaf, 0x64, 0xeb, 0x35, 0x0d, 0x72, 0x1f, 0x8d, 0xbf, 0x07, 0x10, 0xba, 0x45,
	0xda, 0x26, 0x75, 0x51, 0x91, 0x5f, 0x1c, 0x7f, 0x5b, 0xbd, 0x6b, 0x52, 0xda, 0xd6, 0x73, 0xbd,
	0xbb, 0x10, 0x53, 0xd8, 0x6b, 0xca, 0xc2, 0x2c, 0xa5, 0xaa, 0xfc, 0x04, 0x7d, 0x8c, 0x8f, 0xe0,
	0xb0, 0xfb, 0x9e, 0x76, 0xcf, 0xdd, 0x38, 0x07, 0x1d, 0xfe, 0xde, 0x97, 0x39, 0x85, 0x78, 0x41,
	0x6b, 0x31, 0xa7, 0x29, 0xf7, 0x76, 0x0b, 0x07, 0x07, 0xbd, 0xb6, 0x13, 0x9c, 0x00, 0xd0, 0xe7,
	0x86, 0x94, 0xa8, 0xec, 0x41, 0xec, 0xd2, 0xf7, 0xf2, 0x0d, 0x64, 0xf2, 0x2d, 0x80, 0xfd, 0x97,
	0xce, 0x11, 0x6f, 0x48, 0xd9, 0x67, 0xf8, 0x1c, 0xa2, 0xfe, 0x14, 0x78, 0xb7, 0xf7, 0xcb, 0xe5,
	0xdf, 0x2f, 0x4d, 0xb7, 0xa5, 0xfc, 0xd5, 0xae, 0xe0, 0x05, 0x5c, 0xff, 0xe3, 0xa0, 0x78, 0xfc,
	0x37, 0x7d, 0xc3, 0xd0, 0xe9, 0xc9, 0xbf, 0xd2, 0x5d, 0xc5, 0x59, 0xc8, 0x47, 0x7e, 0xfc, 0x2b,
	0x00, 0x00, 0xff, 0xff, 0x22, 0xa7, 0x1c, 0xd7, 0x43, 0x04, 0x00, 0x00,
}
